version: '3.5'

services:
  api1:
    image: api
    hostname: api1
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    image: api
    hostname: api2
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB' 
  nginx:
    image: nginx:latest
    valumes:
    - ./nginx.conf:etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      -"9999:9999"
    deploy:
      resources:
        cpus: '0.25'
        memory: '0.5GB'

  db:
    image: postgres:15
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha